version: '3'

networks:
  webnet:
    driver: bridge

services:
  web:
    ports:
      - '8004:80'
    build:
      context: ./services/web/
      dockerfile: Dockerfile
    container_name: web
    networks:
      - webnet

  live:
    build:
      context: ./
      dockerfile: ./services/live/Dockerfile
    container_name: live
    ports:
      - '8002:8002'
    environment:
      - PORT=8002
      - DATABASE_URL=localhost
      - LOGS_DIR=app/logs/
      - CLASSIFICATION_OUTPUT_DIR=app/results/
      - SPECIES_CLASSIFIER_MODEL_PATH=app/lib/msc/model_e186_2022_10_11_11_18_50.pth
      - EVENT_DETECTOR_MODEL_PATH=app/lib/med/model_presentation_draft_2022_04_07_11_52_08.pth
    volumes:
      - .:/app
    networks:
      - webnet
